Traceback (most recent call last):
  File "/dockvol/tilings/.venv/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/dockvol/tilings/.venv/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/dockvol/tilings/.venv/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/dockvol/tilings/.venv/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/dockvol/tilings/.venv/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/dockvol/tilings/.venv/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/dockvol/tilings/.venv/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
verts = [b.Vertex(xy=[0,0]), b.Vertex(xy=[0,1])]
t = b.Tiling(vertices=verts)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-8-17d1fa0e3de6>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mverts[0m [0;34m=[0m [0;34m[[0m[0mb[0m[0;34m.[0m[0mVertex[0m[0;34m([0m[0mxy[0m[0;34m=[0m[0;34m[[0m[0;36m0[0m[0;34m,[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m,[0m [0mb[0m[0;34m.[0m[0mVertex[0m[0;34m([0m[0mxy[0m[0;34m=[0m[0;34m[[0m[0;36m0[0m[0;34m,[0m[0;36m1[0m[0;34m][0m[0;34m)[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mt[0m [0;34m=[0m [0mb[0m[0;34m.[0m[0mTiling[0m[0;34m([0m[0mvertices[0m[0;34m=[0m[0mverts[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mAttributeError[0m: module 'tilings.base' has no attribute 'Vertex'
AttributeError: module 'tilings.base' has no attribute 'Vertex'

